# Generated by Django 5.1.3 on 2026-07-06 14:30

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthHandoff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('channel_nonce', models.CharField(db_index=True, max_length=64)),
                ('upn', models.CharField(max_length=255)),
                ('oid', models.CharField(max_length=64)),
                ('nombre', models.CharField(blank=True, max_length=255)),
                ('grupos', models.JSONField(default=list)),
                ('es_superadmin', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('consumed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Handoff de autenticación',
                'verbose_name_plural': 'Handoffs de autenticación',
            },
        ),
        migrations.CreateModel(
            name='GrupoEntra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oid', models.CharField(db_index=True, max_length=64, unique=True, verbose_name='Object ID (GUID)')),
                ('nombre', models.CharField(blank=True, max_length=255)),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('creado_por', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'verbose_name': 'Grupo Entra',
                'verbose_name_plural': 'Grupos Entra',
                'ordering': ['nombre', 'oid'],
            },
        ),
        migrations.CreateModel(
            name='PermisoRecurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recurso_key', models.CharField(max_length=64)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('creado_por', models.CharField(blank=True, max_length=255)),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permisos', to='cuentas.grupoentra')),
            ],
            options={
                'verbose_name': 'Permiso',
                'verbose_name_plural': 'Permisos',
                'indexes': [models.Index(fields=['recurso_key'], name='cuentas_per_recurso_d5b0a8_idx')],
                'unique_together': {('grupo', 'recurso_key')},
            },
        ),
    ]
