# Generated by Django 5.1.3 on 2026-07-09 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionRBAC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acceso_total', models.BooleanField(default=False)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('actualizado_por', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'verbose_name': 'Configuración RBAC',
                'verbose_name_plural': 'Configuración RBAC',
            },
        ),
    ]
