# Generated by Django 5.1.3 on 2026-07-06 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('afiliados', '0002_delete_patologia'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_upn', models.CharField(blank=True, max_length=255)),
                ('user_oid', models.CharField(blank=True, db_index=True, max_length=64)),
                ('user_name', models.CharField(blank=True, max_length=255)),
                ('action', models.CharField(choices=[('crear_expediente', 'Crear expediente'), ('subir_archivo', 'Subir archivo'), ('crear_remito', 'Crear remito'), ('asignar_generador', 'Asignar generador'), ('enviar_bonificacion', 'Enviar bonificación'), ('admin_permisos_guardar', 'Guardar permisos'), ('admin_grupo_crear', 'Crear grupo'), ('admin_grupo_eliminar', 'Eliminar grupo')], max_length=64)),
                ('target_type', models.CharField(blank=True, max_length=64)),
                ('target_id', models.CharField(blank=True, max_length=128)),
                ('endpoint', models.CharField(blank=True, max_length=255)),
                ('payload_summary', models.JSONField(blank=True, default=dict)),
                ('response_status', models.IntegerField(blank=True, null=True)),
                ('success', models.BooleanField(default=True)),
                ('error_detail', models.TextField(blank=True)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('dni', models.CharField(blank=True, max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'verbose_name': 'Registro de auditoría',
                'verbose_name_plural': 'Registros de auditoría',
                'ordering': ['-created_at'],
            },
        ),
    ]
