# Generated by Django 5.1.3 on 2026-07-13 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afiliados', '0004_alter_auditlog_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='grupo',
            field=models.CharField(blank=True, db_index=True, max_length=255),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='recurso',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('crear_expediente', 'Crear expediente'), ('subir_archivo', 'Subir archivo'), ('crear_remito', 'Crear remito'), ('asignar_generador', 'Asignar generador'), ('enviar_bonificacion', 'Enviar bonificación'), ('admin_permisos_guardar', 'Guardar permisos'), ('admin_grupo_crear', 'Crear grupo'), ('admin_grupo_eliminar', 'Eliminar grupo'), ('admin_acceso_total', 'Cambiar acceso total'), ('login', 'Inicio de sesión'), ('logout', 'Cierre de sesión'), ('ver_vista', 'Ver pantalla'), ('acceso_denegado', 'Acceso denegado')], db_index=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='user_upn',
            field=models.CharField(blank=True, db_index=True, max_length=255),
        ),
    ]
