# Generated by Django 5.1.3 on 2026-07-14 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afiliados', '0005_auditlog_grupo_auditlog_recurso_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('cotizar', 'Cotizar'), ('crear_expediente', 'Crear expediente'), ('subir_archivo', 'Subir archivo'), ('crear_remito', 'Crear remito'), ('asignar_generador', 'Asignar generador'), ('enviar_bonificacion', 'Enviar bonificación'), ('admin_permisos_guardar', 'Guardar permisos'), ('admin_grupo_crear', 'Crear grupo'), ('admin_grupo_eliminar', 'Eliminar grupo'), ('admin_acceso_total', 'Cambiar acceso total'), ('login', 'Inicio de sesión'), ('logout', 'Cierre de sesión'), ('ver_vista', 'Ver pantalla'), ('acceso_denegado', 'Acceso denegado')], db_index=True, max_length=64),
        ),
    ]
